### ISSUE TITLE
最新版2.3 支持微信7.0.12 么？

### ISSUE THREAD

**Issue by ertmuirm** [chouqibao/ForceWechatDarkMode#9]

**Comment by chouqibao** [comment]
在我的设备上测试是可以的（Play 版 7.0.12 32/64 位），如果你之前用起来没问题，那 7.0.12 应该也没问题。

**Comment by ertmuirm** [comment]
我的Sony XZ1Compact stock rom Android 9 状况如此：
- 微信Play 版 7.0.10 + 太极 Magisk + v2.1 模块 = 深色模式成功
- 微信Play 版 7.0.10 + 太极 Magisk + v2.2 模块 = 不成功
- 微信Play 版 7.0.10 + 太极 Magisk + v2.3 模块 = 不成功 （太极还没支持 v2.3 模块)
- 微信Play 版 7.0.12 + 太极 Magisk + v2.2 模块 = 不成功  (一半黑色比如Action Bar， 另一半白色）
- 微信Play 版 7.0.12 + 太极 Magisk + v2.3 模块 = 不成功 （太极还没支持 v2.3 模块)
